version: '3'

services:
  monitor_node_exporter:
    image: prom/node-exporter:latest
    container_name: monitor_node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"
    restart: unless-stopped
  monitor_cadvisor:
    image: zcube/cadvisor:latest
    container_name: monitor_cadvisor
    ports:
      - 8009:8080
    command:
      - '--docker_only'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"
    restart: unless-stopped
  monitor_prometheus:
    image: prom/prometheus:latest
    container_name: monitor_prometheus
    ports:
      - 4000:9090
    volumes:
      - <directory to store all data>:/prometheus
      - <config file dir>/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"
    restart: unless-stopped